blueprint:
  name: Automatisk Lysstyring
  description: >
    Dette er en automasjon som styrer lys automatisk basert med bevegelsessensorer, dagslys og nattmodus.
  domain: automation
  author: Karl Jørgen Marthinsen
  source_url: https://github.com/karlalskens/Home-Assistant-Lysstyring/blob/main/blueprints/automation/karlalskens_Lysstyring/Automatisk_Lysstyring.yaml
  homeassistant:
    min_version: '2024.6.4'
  input:
    omraade_section:
      name: Område
      icon: mdi:map-marker
      description: Her setter du opp hvilket område av huset som skal styres. Det kan være et rom, eller en del av et større rom.
      input:
        input_booleans:
          name: Velg bryteren for området
          description: Angi hjelpeverdien for området. Må være en input_boolean som begynner med "tilstede_". Har du ikke en fra før, kan du opprette en.
          selector:
            entity:
              domain: input_boolean
              multiple: false
        bypass_boolean:
          name: Velg bryteren som deaktiverer tidsstyringen
          description: Hvilken hjelpeverdi skal brukes til å deaktivere styringen?
          selector:
            entity:
              domain: input_boolean
              multiple: false
    sensorer_section:
      name: Sensorer og tid
      icon: mdi:motion-sensor
      description: Her setter du opp hvilket område av huset som skal styres. Det kan være et rom, eller en del av et større rom.
      input:
        binary_sensors:
          name: Bevegelsessensorer innenfor området (Valgfritt)
          description: Hvilke bevegelsessensorer befinner seg innenfor området?
          default: []
          selector:
            entity:
              domain: binary_sensor
              multiple: true
        utenfor_binary_sensors:
          name: Bevegelsessensorer i utkanten av området (Valgfritt)
          description: Er det noen nærliggende sensorer som skal trigge bevegelse?
          default: []
          selector:
            entity:
              domain: binary_sensor
              multiple: true
        countdown_time:
          name: Velg varighet
          description: Hvor lang tid skal det ta før lyset skal slukkes?
          default: '00:45:00'
          selector:
            duration: {}
        bevegelse_transition_tid:
          name: Vel overgangstid for bevegelse
          description: Hvor lang tid skal det ta for lysene til å dimme når systemet oppdager en bevegelse? Ved problemer - velg 0.
          default: 1
          selector:
            number:
              min: 0
              max: 6
              step: 1
              unit_of_measurement: "s"
              mode: slider
        sol_transition_tid:
          name: Vel overgangstid for døgnsyklus
          description: Hvor lang tid skal det ta for lysene til å dimme når solen går opp eller ned? Ved problemer - velg 0.
          default: 20
          selector:
            number:
              min: 0
              max: 30
              step: 1
              unit_of_measurement: "s"
              mode: slider
    dognsyklus_section:
      name: Sol og døgnsyklus
      icon: mdi:weather-sunset
      description: Dette er innstillinger for soloppgang/-nedgang.
      input:
        grense_for_sol: #Kan gjøres optional hvis triggeren kan deaktiveres
          name: Grense for Sol
          description: Hvor lavt over horisonten skal sola være før det går fra dag til kveld? Legg inn en input_number som definerer hvor høyden i grader. Hvis ingen er definert, brukes 6 grader som standard.
          selector:
            entity:
              domain: input_number
              multiple: false
    scener_section:
      name: Lys og Scener
      icon: mdi:lamps
      description: Vel scenene som skal brukes til lysstyringen. Scenene kan også inneholde innstillinger for andre enheter, som TV, garasjedør, osv.
      input:
        scene_dagtid_aktiv:
          name: Dagtid Aktiv
          description: Når det er dagslys og lyset skal slås på.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_dagtid_passiv:
          name: Dagtid Passiv
          description: Når det er dagslys og lyset skal slås av.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_kveldstid_aktiv:
          name: Kveldstid Aktiv
          description: Når det er kveld/natt og lyset skal slås på.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_kveldstid_passiv:
          name: Kveldstid Passiv
          description: Når det er kveld/natt ute og lyset skal slås av.
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
    nattmodus_section:
      name: Nattmodus
      icon: mdi:weather-night
      description: Dette er innstillinger for nattmodus. Når denne er aktiv, så vil lyset gå til en annen scene når området blir aktivt. Man kan også angi en annen tidsvarighet.
      input:
        nattmodus_boolean:
          name: Velg bryteren for Nattmodus
          description: Angi hjelpeverdien for området. Må være en input_boolean. Har du ikke en fra før, kan du opprette en. Angis den ikke, vil ikke nattmodus fungere på dette området.
          selector:
            entity:
              domain: input_boolean
              multiple: false
        natt_countdown_time:
          name: Velg varighet
          description: Hvor lang tid skal det ta før lyset skal slukkes i nattmodus?
          default: '00:01:00'
          selector:
            duration: {}
        scene_natt_aktiv:
          name: Nattlys Aktiv
          description: Når det er natt og lyset skal slås på.
#          default: []
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
        scene_natt_passiv:
          name: Nattlys Passiv
          description: Når det er natt og lyset skal slås av.
#          default: []
          selector:
            entity:
              multiple: true
              filter:
              - domain:
                - scene
trigger:
  - platform: state #Bevegelsesensor Utløst
    entity_id: !input binary_sensors
    from: "off"
    to: "on"
    id: 'bevegelse_utløst'
  - platform: state #Bevegelsesensor Utløst
    entity_id: !input utenfor_binary_sensors
    from: "off"
    to: "on"
    id: 'utenfor_bevegelse_utløst'
  - platform: state # Område Input_boolean er aktivert
    entity_id: !input input_booleans
    from: "off"
    to: "on"
    id: 'område_boolean_aktivert'
  - platform: state # Område Input_boolean er deaktivert
    entity_id: !input input_booleans
    from: "on"
    to: "off"
    id: 'område_boolean_deaktivert'
  - platform: numeric_state #Solen har gått opp
    entity_id: sun.sun
    attribute: elevation
    above: !input grense_for_sol
    id: 'sol_oppgang'
  - platform: numeric_state #Solen har gått ned
    entity_id: sun.sun
    attribute: elevation
    below: !input grense_for_sol
    id: 'sol_nedgang'
  - platform: state #Nattmodus slått på
    entity_id: !input nattmodus_boolean
    from: "off"
    to: "on"
    id: 'nattmodus_aktivert'
  - platform: state #Nattmodus slått av
    entity_id: !input nattmodus_boolean
    from: "on"
    to: "off"
    id: 'nattmodus_deaktivert'
condition:
  - condition: state #Sjekker om variabel for deaktivering av lysstyring
    entity_id: !input bypass_boolean
    state: "off"
action:
  - variables: #Definerer alle variabler fra skjemaet
      input_input_booleans: !input input_booleans
      input_bypass_boolean: !input bypass_boolean
      input_binary_sensors: !input binary_sensors
      input_utenfor_binary_sensors: !input utenfor_binary_sensors
      input_countdown_time: !input countdown_time
      input_bevegelse_transition_tid: !input bevegelse_transition_tid
      input_sol_transition_tid: !input sol_transition_tid
      input_grense_for_sol: !input grense_for_sol
      input_scene_dagtid_aktiv: !input scene_dagtid_aktiv
      input_scene_dagtid_passiv: !input scene_dagtid_passiv
      input_scene_kveldstid_aktiv: !input scene_kveldstid_aktiv
      input_scene_kveldstid_passiv: !input scene_kveldstid_passiv
      input_nattmodus_boolean: !input nattmodus_boolean
      input_natt_countdown_time: !input natt_countdown_time
      input_scene_natt_aktiv: !input scene_natt_aktiv
      input_scene_natt_passiv: !input scene_natt_passiv
      input_booleans: |-
        {% if is_state(input_input_booleans, 'on') %}
          {{ true }}
        {% else %}
          {{ false }}
        {% endif %}
      nattmodus_boolean: |-
        {% if is_state(input_nattmodus_boolean, 'on') %}
          {{ true }}
        {% else %}
          {{ false }}
        {% endif %}
      countdown_time: |-
        {% if nattmodus_boolean == true %}
          {{ input_natt_countdown_time }}
        {% else %}
          {{ input_countdown_time }}
        {% endif %}
      transition_tid: > # Sette ulik varighet basert på trigger.id
        {{ input_sol_transition_tid if trigger.id == 'sol_oppgang' or trigger.id == 'sol_nedgang' else input_bevegelse_transition_tid }}
      sol_hoyde: "{{ state_attr('sun.sun', 'elevation') }}" #Finne nåværende høyde
      sol_grense: "{{ states(input_grense_for_sol) }}"
      aktuell_scene: |-
        {% if nattmodus_boolean == true %}
          {% if input_booleans == true %}
            {{ input_scene_natt_aktiv }}
          {% else %}
            {{ input_scene_natt_passiv }}
          {% endif %}
        {% else %}
          {% if input_booleans == true and sol_hoyde > sol_grense %}
            {{ input_scene_dagtid_aktiv }}
          {% elif input_booleans == false and sol_hoyde > sol_grense %}
            {{ input_scene_dagtid_passiv }}
          {% elif input_booleans == true and sol_hoyde <= sol_grense %}
            {{ input_scene_kveldstid_aktiv }}
          {% elif input_booleans == false and sol_hoyde <= sol_grense %}
            {{ input_scene_kveldstid_passiv }}
          {% else %}
            none
          {% endif %}
        {% endif %}
  - choose:
      - conditions:
          - condition: not
            conditions:
              - condition: or
                conditions:
                  - condition: trigger #Alt annet enn hvis bevegelse blir oppdaget
                    id: bevegelse_utløst
                  - condition: template
                    value_template: "{{ aktuell_scene == 'none' }}"
        sequence: #Kjør rett scene
          - service: scene.turn_on
            data:
              transition: "{{ transition_tid }}"
            target:
              entity_id: "{{ aktuell_scene }}"
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger # Hvis en bevegelsessensor blir utløst
                id: bevegelse_utløst
              - condition: state # Hvis områdets input_boolean blir slått på
                entity_id: !input input_booleans
                state: "on"
              - condition: and
                conditions:
                  - condition: trigger
                    id: utenfor_bevegelse_utløst
                  - condition: template
                    value_template: "{{ not nattmodus_boolean }}"
        sequence:
          - choose: #Hvis input_boolean er av
              - conditions:
                  - condition: state
                    entity_id: !input input_booleans
                    state: "off"
                sequence:
                  - service: input_boolean.turn_on #Slå på område_boolean
                    target:
                      entity_id: !input input_booleans
          - delay: "{{ countdown_time }}" # La tiden gå!
          - repeat: # Loop som lar tiden gå til alle sensorer er 'off'.
              while:
                - condition: template # Hvis noen av sensorene fremdeles er 'on', skal tiden restartes. Løser typisk problem med IKEA-sensorer.
                  value_template: >-
                    {% set binary_sensors = expand(input_binary_sensors) %}
                    {% set utenfor_sensors = expand(input_utenfor_binary_sensors) %}
                    {% set all_sensors = binary_sensors + utenfor_sensors %}
                    {{ all_sensors | selectattr('state', 'eq', 'on') | list | length > 0 }}
              sequence:
                - delay: "{{ countdown_time }}"
          - service: input_boolean.turn_off
            target:
              entity_id: !input input_booleans
mode: restart